changelog:
  categories:
    - title: Features
      labels:
        - feature
    - title: Fixes
      labels:
        - fix
    - title: Documentation
      labels:
        - documentation
  exclude:
    labels:
      - skip-changelog
